// Structure expected from the Gemini Cloud Function AND stored in Firestore
export interface RecipeData {
    id?: string; // Firestore document ID (added when saving)
    originalUserId?: string; // User who generated it (added when saving)
    prompt?: string; // Prompt used (added when saving)
    createdAt?: Date; // Added when saving
  
    // Fields generated by AI
    title: string;
    description: string;
    prepTime: string; // e.g., "10 mins"
    cookTime: string; // e.g., "20 mins"
    servings: string; // e.g., "2 servings"
    ingredients: string[];
    instructions: string[];
    calories: string | number | null; // e.g., "approx 450 kcal" or 450 or null
    difficulty: 'Easy' | 'Medium' | 'Hard' | string | null; // AI might return variations
    notes?: string | null;
    imageUrl?: string | null; // For future AI images
    aiModelUsed?: string; // Added when saving
  }